import '../styles/globals.css'
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css'
import 'animate.css/animate.min.css';
import { useEffect, useState } from 'react';
import Loading from '../components/Loading';
import { Auth } from '../contexts/auth'
import { User } from '../contexts/user'
import { IBGE } from '../contexts/ibge';

function MyApp({ Component, pageProps }) {

  let [loading, setLoading] = useState(true)

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoading(false);
    }
  });

  return (
    <>
      {loading ?
        <>
          <Loading />
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>
        </>
        :
        <>
          <Head>
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by create Beneficiário Prime" />
            <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
            />
          </Head>
          <IBGE>
            <Auth>
              <User>
                <Component {...pageProps} />
              </User>
            </Auth>
          </IBGE>
        </>
      }
    </>
  );
}

export default MyApp
