import '../styles/globals.css'
import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css'
import 'animate.css/animate.min.css';
import { useEffect, useState } from 'react';
import Loading from '../components/Loading';
import { Auth } from '../contexts/auth'

function MyApp({ Component, pageProps }) {

  let [loading, setLoading] = useState(true)

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoading(false);
    }
  });

  return (
    <>
      {loading ?
        <>
          <Loading />
          <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossOrigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossOrigin="anonymous"></script>
        </>
        :
        <>
          <Head>
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by create Beneficiário Prime" />
            <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
            />
          </Head>
          <Auth>
            <Component {...pageProps} />
          </Auth>
        </>
      }
    </>
  );
}

export default MyApp
