import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import React, { useEffect, useState } from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Beneficiário Prime</title>
        <meta name="description" content="Generated by create Beneficiário Prime" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <header className={styles.container}>
        <div className={`container-fluid ${styles.containerFluid}`}>
          <div className={`${cardHeader}`}>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Special title treatment</h5>
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
        </div>
      </header>
    </>
  )
}
