import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import React, { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faCommentMedical,
  faMapMarkerAlt,
  faCalendarAlt,
  faCreditCard,
  faThumbsUp,
  faStethoscope,
  faVideo,
  faMicroscope,
  faCrutch,
  faNotesMedical
} from '@fortawesome/free-solid-svg-icons'

const ButtonOptions = props => {
  return (
    <button
      className={`${styles.buttonOptions} ${props.className}`}
      title={props.title}
      onClick={props.onClick}
      onChange={props.onChange}
    >{props.children}
    </button>
  )
}

const FormOptions = props => {
  return (
    <div className={`form-floating mb-2 ${props.className}`}>
      <input autoComplete="off" autoCapitalize="none" list={props.list} type="text" className={`form-control`}
        placeholder={props.placeholder}
        id={props.for} />
      <label
        for={props.for}
      >{props.children}</label>
    </div>
  )
}

const CardOffers = props => {
  return (
    <div className={`card ${styles.cardOffers} ${props.className}`}>
      <div className="card-body">
        {props.children}
      </div>
    </div>
  )
}


export default function Home() {

  return (
    <>
      <Head>
        <title>Beneficiário Prime</title>
        <meta name="description" content="Generated by create Beneficiário Prime" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <header className={styles.container}>
        <div className={`container-fluid ${styles.containerFluid}`}>
          <div className={`d-flex flex-row-reverse`}>
            <div className={`${styles.content}`}>
              <h1 className={`${styles.title}`}>Conteúdo pra botar pra baixo, será que <br /> funciona?</h1>
              <h4>Exercitation dolore et ad laborum labore cillum deserunt id. <br />Ut fugiat aliquip est labore consequat irure esse sint do cupidatat.</h4>
              <div className={`card mt-4 ${styles.card}`}>
                <div className="card-body">
                  <div className="mb-3">
                    <ButtonOptions><span><FontAwesomeIcon icon={faStethoscope} /></span> Consultas Presenciais</ButtonOptions>
                    <ButtonOptions><span><FontAwesomeIcon icon={faVideo} /></span> Telemedicina</ButtonOptions>
                    <ButtonOptions><span><FontAwesomeIcon icon={faMicroscope} /></span> Exames</ButtonOptions>
                    <ButtonOptions><span><FontAwesomeIcon icon={faCrutch} /></span> Vacinas</ButtonOptions>
                    <ButtonOptions><span><FontAwesomeIcon icon={faNotesMedical} /></span> Procedimentos</ButtonOptions>
                  </div>
                  <FormOptions placeholder="São Paulo" list="cidades" for="estado">Selecione uma cidade</FormOptions>
                  <datalist id="cidades">
                    <option>Cidade 1</option>
                    <option>Cidade 2</option>
                  </datalist>
                  <FormOptions placeholder="Dentista" for="especialidade">Digite ou escolha uma especialidade</FormOptions>
                  <div className="d-flex">
                    <FormOptions placeholder="Dentista" className="flex-grow-1" for="cidade">Escolha um bairro disponível</FormOptions>
                    <div className="d-flex align-items-center">
                      <button className={`ms-3 ${styles.buttonSend}`}>Buscar</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <section className={styles.container}>
        <div className={`${styles.containerFluid} container-fluid`} style={{ backgroundColor: "#666666" }}>
          <div className={`d-flex`}>
            <div className={`${styles.content} ${styles.contentCardOffers} d-flex mb-5 mt-5`}>
              <CardOffers>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </CardOffers>
              <CardOffers>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </CardOffers>
              <CardOffers className={`${styles.cardRed}`}>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </CardOffers>
            </div>
          </div>
        </div>
      </section>
      <div className={`${styles.container}`}>
        <div className={`${styles.containerFluid} container-fluid`} style={{ backgroundColor: "#CFDBF9", color: "#FFFFFF" }}>
          <div className={`card-title mt-5 mb-5`}>
            <h1>Olá</h1>
          </div>
          <div className={`${styles.boxScheduling} `}>
            <div className={`${styles.iconScheduling}`}>
              <figure>
                <FontAwesomeIcon icon={faCommentMedical} />
              </figure>
              <p>Selecione o tipo de atendimento</p>
            </div>
            <div className={`${styles.iconScheduling}`}>
              <figure>
                <FontAwesomeIcon icon={faMapMarkerAlt} />
              </figure>
              <p>Escolha o local</p>
            </div>
            <div className={`${styles.iconScheduling}`}>
              <figure>
                <FontAwesomeIcon icon={faCalendarAlt} />
              </figure>
              <p>Faça sua sugestão da data e hora</p>
            </div>
            <div className={`${styles.iconScheduling}`}>
              <figure>
                <FontAwesomeIcon icon={faCreditCard} />
              </figure>
              <p>Realize o pagamento</p>
            </div>
            <div className={`${styles.iconScheduling}`}>
              <figure>
                <FontAwesomeIcon icon={faThumbsUp} />
              </figure>
              <p>Aguarde a confirmação do agendamento</p>
            </div>
          </div>
        </div>
      </div>
      <div className={`${styles.container}`}>
        <div className={`${styles.containerFluid} container-fluid`} style={{ backgroundColor: "#f4f4f4" }}>
          <div className={`mt-5 mb-5 d-flex justify-content-between`}>
            <div className={``}>
              <div className={`mb-4`}>
                <h1>VANTAGENS DE SER</h1>
                <h1>Beneficiário Prime</h1>
              </div>
              <div className={`d-flex`}>
                <div className={`${styles.benefits}`}>
                  <ul>
                    <li>A partir de R$ 13,75 por pessoa</li>
                    <li>Consultas médicas com até 90% de desconto</li>
                    <li>Exames e Procedimentos com até 100% de desconto</li>
                  </ul>
                </div>
                <div className={`${styles.benefits}`}>
                  <ul>
                    <li>Até 4 beneficiários por cartão</li>
                    <li>Retorno médico Gratuito!</li>
                    <li>Sem nenhuma carência!</li>
                    <li>Agendamento fácil, via telefone, site ou celular</li>
                  </ul>
                </div>
              </div>
            </div>
            <div className={``}>
              <h1>IMAGEM</h1>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
